<a href="https://colab.research.google.com/github/Vputri/Rekayasa-Komputasi/blob/main/Rekayasan_Perangkat_Lunak_Tugas_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matriks

**Penjumlahan**




In [ ]:
import numpy as np

A = np.array([[2, 3, 5], [4, 1, 2]])
B = np.array([[1, 2, 6], [3, 2, 1]])
C = A + B
print(C)

[[ 3  5 11]
 [ 7  3  3]]


**Pengurangan**

In [ ]:
A = np.array([[2, 6], [-4, 1], [3, 2]])
B = np.array([[6, -2], [4, 1], [0, 3]])
C = A - B
print(C)

[[-4  8]
 [-8  0]
 [ 3 -1]]


**Perkalian Skalar**

In [ ]:
A = np.array([[2, 6], [-4, 1], [3, 2]])
C = 2 * A
print(C)

[[ 4 12]
 [-8  2]
 [ 6  4]]


**Perkalian Matriks dengan Matriks**

In [ ]:
A = np.array([[2, 1, -6], [1, -3, 2]])
B = np.array([[1, 0, -3], [0, 4, 2], [-2, 1, 1]])
C = A.dot(B)
print(C)

[[ 14  -2 -10]
 [ -3 -10  -7]]


**Determinan**

In [ ]:
A = np.array([[3, -7], [-9, 5]])
determinan = np.linalg.det(A)
print(round(determinan))

-48


In [ ]:
A = np.array([[3, 0, -2], [6, -8, 1], [0, 3, 4]])
determinan = np.linalg.det(A)
print(round(determinan))

-141


**Invers**

In [ ]:
A = np.array([[1, 2, 3], [2, 4, 3], [6, 1, 4]])
invers = np.linalg.inv(A)
print(invers)

[[-0.39393939  0.15151515  0.18181818]
 [-0.3030303   0.42424242 -0.09090909]
 [ 0.66666667 -0.33333333  0.        ]]


**Metode Eliminasi Gauss**

In [ ]:
import sys

n = int(input('Masukkan jumlah variabel yang tidak diketahui: '))
a = np.zeros((n,n+1))
x = np.zeros(n)

In [ ]:
print('Masukkan Augmented Matrix Coefficients:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Terdekeksi dibagi dengan nol')
        
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
        
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]

Proses Substitusi Mundur

In [ ]:
x[n-1] = a[n-1][n]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
    
    x[i] = x[i]/a[i][i]

Solusi

In [ ]:
print('\nSolusinya adalah: ')
for i in range(n):
    print('X%d = %f' %(i,x[i]), end = '\t')


**Metode Eliminasi Gauss Seidell**

inisialisasi matrik A

In [ ]:
from numpy import array,zeros

A = array([[10.,-1.,2.,0.],
           [-1.,11.,-1.,3.],
           [2.,-1.,10.,-1.],
           [0.,3.,-1.,8.]])
print(A)

[[10. -1.  2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]]


inisialisasi vektor b

In [ ]:
b = array([[6.],
           [25],
           [-11],
           [15]])
print(b)

[[  6.]
 [ 25.]
 [-11.]
 [ 15.]]


In [ ]:
n=len(A)
iterasi=500
toleransi=0.0001
xlama=zeros((n,1))
xbaru=zeros((n,1))
c=zeros((n,1))
T=zeros((n,n))

Menghitung matrik T dan vektor c

In [ ]:
for j in range(0,n-1):
  for i in range(0,n):
    if i==j:
      i=i+1
    T[j][i]=-1.*A[j][i]/A[j][j]
  c[j][0]=b[j][0]/A[j][j]

j=n-1
for i in range(0,n-1):
  T[j][i]=-1.*A[j][i]/A[j][j]
c[j][0]=b[j][0]/A[j][j]

Metode Gauss-Seidel

In [ ]:
for m in range(1,iterasi):
  S=0
  for i in range(0,n):
    S=S+T[0][i]*xlama[i][0]
  xbaru[0][0]=S+c[0][0]

  for k in range(1,n):
    P=0
    for j in range(0,k):
      P=P+T[k][j]*xbaru[j][0]
    S=0

    for i in range(k,n):
      S=S+T[k][i]*xlama[i][0]
    xbaru[k][0]=P+S+c[k][0]

  x=xbaru-xlama

  xlama=xbaru.copy()

Mencetak hasil perhitungan

In [ ]:
print('iterasi ke', m)
print(xbaru)

iterasi ke 499
[[ 1.]
 [ 2.]
 [-1.]
 [ 1.]]


**Metode Dekomposisi LU**

inisialisasi matrik augment

In [ ]:
from numpy import array,zeros

A = array([[1, 0, -2, 7],
           [2, -1, 3, 4],
           [3, -3, 1, 5],
           [2, 1, 4, 4]])
print(A)

[[ 1  0 -2  7]
 [ 2 -1  3  4]
 [ 3 -3  1  5]
 [ 2  1  4  4]]


In [ ]:
b = array([[11],
           [9],
           [8],
           [10]])
print(b)

[[11]
 [ 9]
 [ 8]
 [10]]


In [ ]:
n = len(A)
L = zeros((n,n))

for i in range(0,n):
  L[i][i]=1

Proses Triangularisasi

In [ ]:
for k in range(0,n-1):
  #pivot
  if A[k][k]==0:
    for s in range(0,n):
      v=A[k][s]
      u=A[k+1][s]
      A[k][s]=u
      A[k+1][s]=v

  for j in range(k+1,n):
    m=A[j][k]/A[k][k]
    L[j][k]=m
    for i in range(0,n):
      A[j][i]=A[j][i]-m*A[k][i]

In [ ]:
U = zeros((n,n))
for i in range(0,n):
  for j in range(0,n):
    U[i][j]=A[i][j]

Proses Substitusi Maju

In [ ]:
y = zeros((n,1))
y[0][0]=b[0][0]/L[0][0]
for j in range(1,n):
  S=0
  for i in range(0,j):
    S=S+y[i][0]*L[j][i]
  y[j][0]=b[j][0]-S

Proses Substitusi Mundur

In [ ]:
x=zeros((n,1))
x[n-1][0]=y[n-1][0]/U[n-1][n-1]

for j in range(n-2,-1,-1):
  S=0
  for i in range(j+1,n):
    S=S+U[j][i]*x[i][0]
  x[j][0]=(y[j][0]-S)/U[j][j]

print(x)

[[-1.]
 [-0.]
 [ 1.]
 [ 2.]]
